"""initial schema — public_corpus tables, enums, indexes

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-01

The initial migration is hand-written rather than autogenerated because:
  - Postgres ENUM types need explicit creation order (before tables that use them)
  - GENERATED ALWAYS AS ... STORED columns aren't well-supported by autogen
  - pgvector indexes (HNSW) need raw SQL
  - The articles ↔ article_versions FK loop requires ALTER TABLE after creation

Subsequent migrations CAN use autogenerate; the ORM in services/corpus/models.py
mirrors this schema (minus the generated tsvector columns, which the repository
queries via raw SQL).
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SCHEMA = "public_corpus"


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {SCHEMA}")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # --- Enums ---------------------------------------------------------
    op.execute(
        f"""
        CREATE TYPE {SCHEMA}.legal_category AS ENUM (
            'constitution', 'code', 'loi', 'decret', 'arrete',
            'circulaire', 'convention'
        )
        """
    )
    op.execute(
        f"""
        CREATE TYPE {SCHEMA}.code_subcategory AS ENUM (
            'code_civil', 'code_penal', 'code_travail', 'code_commerce',
            'code_rural', 'code_procedure_civile', 'code_procedure_penale',
            'autre'
        )
        """
    )
    op.execute(
        f"CREATE TYPE {SCHEMA}.legal_status AS ENUM "
        "('in_force', 'abrogated', 'partially_abrogated')"
    )
    op.execute(
        f"CREATE TYPE {SCHEMA}.editorial_status AS ENUM "
        "('draft', 'pending_review', 'published', 'rejected')"
    )
    op.execute(
        f"CREATE TYPE {SCHEMA}.heading_level AS ENUM "
        "('book', 'title', 'chapter', 'section', 'subsection')"
    )
    op.execute(
        f"""
        CREATE TYPE {SCHEMA}.court_type AS ENUM (
            'cassation', 'appel', 'tpi',
            'tribunal_commerce', 'tribunal_enfants', 'autre'
        )
        """
    )
    op.execute(
        f"CREATE TYPE {SCHEMA}.citation_node_type AS ENUM "
        "('article', 'decision', 'legal_text')"
    )
    op.execute(
        f"""
        CREATE TYPE {SCHEMA}.citation_relation AS ENUM (
            'cites', 'applies', 'interprets', 'distinguishes',
            'amends', 'abrogates', 'supersedes'
        )
        """
    )
    op.execute(
        f"CREATE TYPE {SCHEMA}.raw_document_type AS ENUM "
        "('moniteur', 'code_book', 'decision', 'decree', 'other')"
    )
    op.execute(
        f"CREATE TYPE {SCHEMA}.raw_document_status AS ENUM "
        "('pending', 'extracting', 'extracted', 'failed')"
    )
    op.execute(
        f"CREATE TYPE {SCHEMA}.raw_page_status AS ENUM "
        "('pending', 'ocr_done', 'review_needed', 'reviewed')"
    )
    op.execute(
        f"CREATE TYPE {SCHEMA}.extraction_method AS ENUM "
        "('regex', 'llm', 'manual')"
    )

    # --- raw_documents -------------------------------------------------
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.raw_documents (
            id              SERIAL PRIMARY KEY,
            document_type   {SCHEMA}.raw_document_type NOT NULL,
            source_url      TEXT,
            storage_path    TEXT NOT NULL,
            original_filename TEXT,
            sha256_hash     TEXT NOT NULL UNIQUE,
            file_size_bytes BIGINT,
            mime_type       TEXT,
            acquired_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            source_metadata JSONB,
            status          {SCHEMA}.raw_document_status NOT NULL DEFAULT 'pending'
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_raw_documents_status ON {SCHEMA}.raw_documents(status)"
    )

    # --- raw_pages -----------------------------------------------------
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.raw_pages (
            id              SERIAL PRIMARY KEY,
            raw_document_id INTEGER NOT NULL
                REFERENCES {SCHEMA}.raw_documents(id) ON DELETE CASCADE,
            page_number     INTEGER NOT NULL,
            image_path      TEXT,
            ocr_text        TEXT,
            ocr_blocks      JSONB,
            ocr_engine      TEXT,
            ocr_confidence  NUMERIC(4,3),
            ocr_status      {SCHEMA}.raw_page_status NOT NULL DEFAULT 'pending',
            created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_raw_pages_doc_page UNIQUE (raw_document_id, page_number)
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_raw_pages_document ON {SCHEMA}.raw_pages(raw_document_id)"
    )
    op.execute(
        f"CREATE INDEX ix_raw_pages_status ON {SCHEMA}.raw_pages(ocr_status)"
    )

    # --- legal_texts ---------------------------------------------------
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.legal_texts (
            id                  SERIAL PRIMARY KEY,
            slug                TEXT NOT NULL UNIQUE,
            category            {SCHEMA}.legal_category NOT NULL,
            code_subcategory    {SCHEMA}.code_subcategory,
            jurisdiction        TEXT NOT NULL DEFAULT 'HT',
            title_fr            TEXT NOT NULL,
            title_ht            TEXT,
            description_fr      TEXT,
            description_ht      TEXT,
            preamble_fr         TEXT,
            preamble_ht         TEXT,
            promulgation_date   DATE,
            publication_date    DATE,
            moniteur_ref        TEXT,
            status              {SCHEMA}.legal_status NOT NULL DEFAULT 'in_force',
            editorial_status    {SCHEMA}.editorial_status NOT NULL DEFAULT 'draft',
            source_document_id  INTEGER
                REFERENCES {SCHEMA}.raw_documents(id) ON DELETE SET NULL,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            published_at        TIMESTAMPTZ
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_legal_texts_category ON {SCHEMA}.legal_texts(category)"
    )
    op.execute(
        f"CREATE INDEX ix_legal_texts_subcategory ON {SCHEMA}.legal_texts(code_subcategory)"
    )
    op.execute(
        f"CREATE INDEX ix_legal_texts_status ON {SCHEMA}.legal_texts(status)"
    )
    op.execute(
        f"CREATE INDEX ix_legal_texts_editorial_status "
        f"ON {SCHEMA}.legal_texts(editorial_status)"
    )
    op.execute(
        f"CREATE INDEX ix_legal_texts_publication "
        f"ON {SCHEMA}.legal_texts(publication_date DESC NULLS LAST)"
    )

    # --- legal_headings ------------------------------------------------
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.legal_headings (
            id              SERIAL PRIMARY KEY,
            legal_text_id   INTEGER NOT NULL
                REFERENCES {SCHEMA}.legal_texts(id) ON DELETE CASCADE,
            parent_id       INTEGER
                REFERENCES {SCHEMA}.legal_headings(id) ON DELETE CASCADE,
            level           {SCHEMA}.heading_level NOT NULL,
            key             TEXT NOT NULL,
            number          TEXT,
            title_fr        TEXT,
            title_ht        TEXT,
            content_fr      TEXT,
            content_ht      TEXT,
            position        INTEGER NOT NULL DEFAULT 0,
            CONSTRAINT uq_legal_headings_text_key UNIQUE (legal_text_id, key)
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_legal_headings_text "
        f"ON {SCHEMA}.legal_headings(legal_text_id)"
    )
    op.execute(
        f"CREATE INDEX ix_legal_headings_parent "
        f"ON {SCHEMA}.legal_headings(parent_id)"
    )
    op.execute(
        f"CREATE INDEX ix_legal_headings_position "
        f"ON {SCHEMA}.legal_headings(legal_text_id, position)"
    )

    # --- legal_signers -------------------------------------------------
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.legal_signers (
            id              SERIAL PRIMARY KEY,
            legal_text_id   INTEGER NOT NULL
                REFERENCES {SCHEMA}.legal_texts(id) ON DELETE CASCADE,
            name            TEXT NOT NULL,
            function_fr     TEXT NOT NULL,
            function_ht     TEXT,
            position        INTEGER NOT NULL DEFAULT 0
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_legal_signers_text "
        f"ON {SCHEMA}.legal_signers(legal_text_id)"
    )

    # --- articles ------------------------------------------------------
    # current_version_id FK is added later (loop with article_versions).
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.articles (
            id                  SERIAL PRIMARY KEY,
            legal_text_id       INTEGER NOT NULL
                REFERENCES {SCHEMA}.legal_texts(id) ON DELETE CASCADE,
            heading_id          INTEGER
                REFERENCES {SCHEMA}.legal_headings(id) ON DELETE SET NULL,
            number              TEXT NOT NULL,
            slug                TEXT NOT NULL,
            current_version_id  INTEGER,
            domain_tags         TEXT[] NOT NULL DEFAULT '{{}}',
            position            INTEGER NOT NULL DEFAULT 0,
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_articles_text_number UNIQUE (legal_text_id, number),
            CONSTRAINT uq_articles_text_slug UNIQUE (legal_text_id, slug)
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_articles_text ON {SCHEMA}.articles(legal_text_id)"
    )
    op.execute(
        f"CREATE INDEX ix_articles_heading ON {SCHEMA}.articles(heading_id)"
    )
    op.execute(
        f"CREATE INDEX ix_articles_position ON {SCHEMA}.articles(legal_text_id, position)"
    )

    # --- article_versions ----------------------------------------------
    # search_vector_fr/ht are GENERATED ALWAYS AS ... STORED columns.
    # The 'french' regconfig handles French stemming; for Kreyòl we use
    # 'simple' (no stemming) until/unless we ship a dedicated dictionary.
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.article_versions (
            id                  SERIAL PRIMARY KEY,
            article_id          INTEGER NOT NULL
                REFERENCES {SCHEMA}.articles(id) ON DELETE CASCADE,
            version_number      INTEGER NOT NULL DEFAULT 1,
            title_fr            TEXT,
            title_ht            TEXT,
            text_fr             TEXT NOT NULL,
            text_ht             TEXT,
            effective_from      DATE,
            effective_to        DATE,
            source_amendment_id INTEGER
                REFERENCES {SCHEMA}.legal_texts(id) ON DELETE SET NULL,
            confidence          NUMERIC(4,3),
            editorial_status    {SCHEMA}.editorial_status NOT NULL DEFAULT 'draft',
            search_vector_fr    TSVECTOR GENERATED ALWAYS AS (
                to_tsvector('french',
                    coalesce(title_fr, '') || ' ' || coalesce(text_fr, ''))
            ) STORED,
            search_vector_ht    TSVECTOR GENERATED ALWAYS AS (
                to_tsvector('simple',
                    coalesce(title_ht, '') || ' ' || coalesce(text_ht, ''))
            ) STORED,
            embedding           vector(1024),
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            CONSTRAINT uq_article_versions_article_n UNIQUE (article_id, version_number)
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_article_versions_article "
        f"ON {SCHEMA}.article_versions(article_id)"
    )
    op.execute(
        f"CREATE INDEX ix_article_versions_effective "
        f"ON {SCHEMA}.article_versions(article_id, effective_from)"
    )
    op.execute(
        f"CREATE INDEX ix_article_versions_editorial_status "
        f"ON {SCHEMA}.article_versions(editorial_status)"
    )
    op.execute(
        f"CREATE INDEX ix_article_versions_search_fr "
        f"ON {SCHEMA}.article_versions USING GIN (search_vector_fr)"
    )
    op.execute(
        f"CREATE INDEX ix_article_versions_search_ht "
        f"ON {SCHEMA}.article_versions USING GIN (search_vector_ht)"
    )
    # HNSW supports empty tables in pgvector >= 0.5.0.
    op.execute(
        f"CREATE INDEX ix_article_versions_embedding "
        f"ON {SCHEMA}.article_versions USING hnsw (embedding vector_cosine_ops)"
    )

    # --- close the FK loop on articles.current_version_id --------------
    op.execute(
        f"""
        ALTER TABLE {SCHEMA}.articles
        ADD CONSTRAINT fk_articles_current_version
        FOREIGN KEY (current_version_id)
        REFERENCES {SCHEMA}.article_versions(id)
        ON DELETE SET NULL
        """
    )

    # --- decisions -----------------------------------------------------
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.decisions (
            id                  SERIAL PRIMARY KEY,
            slug                TEXT NOT NULL UNIQUE,
            court               {SCHEMA}.court_type NOT NULL,
            chamber             TEXT,
            formation           TEXT,
            case_number         TEXT,
            decision_date       DATE NOT NULL,
            parties_anonymized  BOOLEAN NOT NULL DEFAULT TRUE,
            summary_fr          TEXT,
            summary_ht          TEXT,
            headnotes_fr        TEXT,
            headnotes_ht        TEXT,
            full_text_fr        TEXT,
            full_text_ht        TEXT,
            outcome             TEXT,
            source_document_id  INTEGER
                REFERENCES {SCHEMA}.raw_documents(id) ON DELETE SET NULL,
            editorial_status    {SCHEMA}.editorial_status NOT NULL DEFAULT 'draft',
            search_vector_fr    TSVECTOR GENERATED ALWAYS AS (
                to_tsvector('french',
                    coalesce(summary_fr, '') || ' ' ||
                    coalesce(headnotes_fr, '') || ' ' ||
                    coalesce(full_text_fr, ''))
            ) STORED,
            search_vector_ht    TSVECTOR GENERATED ALWAYS AS (
                to_tsvector('simple',
                    coalesce(summary_ht, '') || ' ' ||
                    coalesce(headnotes_ht, '') || ' ' ||
                    coalesce(full_text_ht, ''))
            ) STORED,
            embedding           vector(1024),
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
            published_at        TIMESTAMPTZ
        )
        """
    )
    op.execute(f"CREATE INDEX ix_decisions_court ON {SCHEMA}.decisions(court)")
    op.execute(
        f"CREATE INDEX ix_decisions_date ON {SCHEMA}.decisions(decision_date DESC)"
    )
    op.execute(
        f"CREATE INDEX ix_decisions_editorial_status "
        f"ON {SCHEMA}.decisions(editorial_status)"
    )
    op.execute(
        f"CREATE INDEX ix_decisions_search_fr "
        f"ON {SCHEMA}.decisions USING GIN (search_vector_fr)"
    )
    op.execute(
        f"CREATE INDEX ix_decisions_search_ht "
        f"ON {SCHEMA}.decisions USING GIN (search_vector_ht)"
    )
    op.execute(
        f"CREATE INDEX ix_decisions_embedding "
        f"ON {SCHEMA}.decisions USING hnsw (embedding vector_cosine_ops)"
    )

    # --- citations -----------------------------------------------------
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.citations (
            id                  SERIAL PRIMARY KEY,
            source_node_type    {SCHEMA}.citation_node_type NOT NULL,
            source_node_id      INTEGER NOT NULL,
            target_node_type    {SCHEMA}.citation_node_type NOT NULL,
            target_node_id      INTEGER NOT NULL,
            relation            {SCHEMA}.citation_relation NOT NULL,
            source_paragraph    TEXT,
            confidence          NUMERIC(4,3),
            extraction_method   {SCHEMA}.extraction_method,
            validated_by        TEXT,
            editorial_status    {SCHEMA}.editorial_status NOT NULL DEFAULT 'draft',
            created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_citations_source "
        f"ON {SCHEMA}.citations(source_node_type, source_node_id)"
    )
    op.execute(
        f"CREATE INDEX ix_citations_target "
        f"ON {SCHEMA}.citations(target_node_type, target_node_id)"
    )
    op.execute(f"CREATE INDEX ix_citations_relation ON {SCHEMA}.citations(relation)")
    op.execute(
        f"CREATE INDEX ix_citations_editorial_status "
        f"ON {SCHEMA}.citations(editorial_status)"
    )

    # --- editorial_actions ---------------------------------------------
    op.execute(
        f"""
        CREATE TABLE {SCHEMA}.editorial_actions (
            id          SERIAL PRIMARY KEY,
            actor       TEXT NOT NULL,
            action      TEXT NOT NULL,
            target_type TEXT NOT NULL,
            target_id   INTEGER NOT NULL,
            diff        JSONB,
            comment     TEXT,
            timestamp   TIMESTAMPTZ NOT NULL DEFAULT NOW()
        )
        """
    )
    op.execute(
        f"CREATE INDEX ix_editorial_actions_target "
        f"ON {SCHEMA}.editorial_actions(target_type, target_id)"
    )
    op.execute(
        f"CREATE INDEX ix_editorial_actions_actor_time "
        f"ON {SCHEMA}.editorial_actions(actor, timestamp DESC)"
    )


def downgrade() -> None:
    # Drop tables in reverse dependency order.
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.editorial_actions CASCADE")
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.citations CASCADE")
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.decisions CASCADE")
    # Break the FK loop before dropping articles/article_versions.
    op.execute(
        f"ALTER TABLE IF EXISTS {SCHEMA}.articles "
        f"DROP CONSTRAINT IF EXISTS fk_articles_current_version"
    )
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.article_versions CASCADE")
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.articles CASCADE")
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.legal_signers CASCADE")
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.legal_headings CASCADE")
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.legal_texts CASCADE")
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.raw_pages CASCADE")
    op.execute(f"DROP TABLE IF EXISTS {SCHEMA}.raw_documents CASCADE")

    # Drop enums.
    for enum_name in (
        "extraction_method",
        "raw_page_status",
        "raw_document_status",
        "raw_document_type",
        "citation_relation",
        "citation_node_type",
        "court_type",
        "heading_level",
        "editorial_status",
        "legal_status",
        "code_subcategory",
        "legal_category",
    ):
        op.execute(f"DROP TYPE IF EXISTS {SCHEMA}.{enum_name}")

    # Note: we leave the schema and the `vector` extension in place,
    # since they may be used by other migrations / databases.
